/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.IntelliJ_Hendrice_Remy_Plan2Track;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import org.helmo.IntelliJ_Hendrice_Remy_Plan2Track.view.MainWindow;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Parent root = new VBox();



        MainWindow view = new MainWindow();

        Scene scene = new Scene(root, 300,275);

        primaryStage.setTitle("Planner");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

}
